server:
  port: 9001
spring:
  application:
    name: caspar-user #指定服务器名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.179.9:33306/tensquare_user?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true